name=EDP-Persistence-Arduino
version=0.1.0
author=Simon J. Stuart
maintainer=Simon J. Stuart
sentence=Arduino-ESP32 concrete Persistence providers for the ESPressio Development Platform.
paragraph=FileSystemStorage and PreferencesKeyValueStorage providers implementing EDP-Persistence with Arduino-ESP32 filesystem and Preferences APIs.
category=Other
url=https://espressio.org
architectures=esp32
includes=ESPressio_Persistence_Arduino.hpp
depends=EDP-Persistence (>=0.1.0 && <0.2.0),EDP-Memory (>=0.1.0 && <0.2.0)
